@url = http://localhost:5000/conferences-module
@conferenceId = ff7f4016-4334-4983-8d8c-8732d60394cf
@hostId = 0b76b5f7-18f6-43b8-a8dc-aeb4c77fca47

###
GET {{url}}

###
GET {{url}}/hosts

###
GET {{url}}/hosts/{{hostId}}

###
POST {{url}}/hosts
Content-Type: application/json

{
  "name": "Host 1",
  "description": "Lorem ipsum"
}

###
PUT {{url}}/hosts/{{hostId}}
Content-Type: application/json

{
  "name": "Host 2",
  "description": "Lorem ipsum"
}

###
DELETE {{url}}/hosts/{{hostId}}

###
GET {{url}}/conferences

###
GET {{url}}/conferences/{{conferenceId}}

###
POST {{url}}/conferences
Content-Type: application/json

{
  "hostId": "{{hostId}}",
  "name": "Conference 1",
  "location": "Test street 123",
  "description": "Lorem ipsum",
  "from": "2021-03-01",
  "to": "2021-03-02"
}

###
PUT {{url}}/conferences/{{conferenceId}}
Content-Type: application/json

{
  "hostId": "{{hostId}}",
  "name": "Conference 2",
  "location": "Test street 123",
  "description": "Lorem ipsum",
  "from": "2021-03-01",
  "to": "2021-03-02"
}

###
DELETE {{url}}/conferences/{{conferenceId}}